# Generated by Django 5.0.3 on 2024-04-22 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandmarkIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('url_for_image', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField(default=0.0)),
                ('lon', models.FloatField(default=0.0)),
                ('place', models.CharField(default='Unknown', max_length=100)),
                ('facing', models.CharField(default='Unknown', max_length=100)),
                ('speed', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Itineraries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('it_name', models.CharField(max_length=200)),
                ('city_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_day', models.FloatField(default=0)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('it_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.itineraries')),
            ],
        ),
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('city_name', models.CharField(max_length=100)),
                ('country_name', models.CharField(max_length=100)),
                ('description', models.CharField(default='Unknown')),
                ('tags', models.ManyToManyField(to='api.tag')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=150)),
                ('biography', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('art', models.FloatField(default=3, null=True)),
                ('architecture', models.FloatField(default=3, null=True)),
                ('beach', models.FloatField(default=3, null=True)),
                ('entertainment', models.FloatField(default=3, null=True)),
                ('food', models.FloatField(default=3, null=True)),
                ('hiking', models.FloatField(default=3, null=True)),
                ('history', models.FloatField(default=3, null=True)),
                ('mountains', models.FloatField(default=3, null=True)),
                ('museum', models.FloatField(default=3, null=True)),
                ('music', models.FloatField(default=3, null=True)),
                ('recreation', models.FloatField(default=3, null=True)),
                ('scenicViews', models.FloatField(default=3, null=True)),
                ('sports', models.FloatField(default=3, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisitedLandmarks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_time', models.DateTimeField()),
                ('rating', models.FloatField(default=3)),
                ('image_url', models.URLField(blank=True, max_length=255, null=True)),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landmark')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
