# Generated by Django 5.0.3 on 2024-03-25 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itineraries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('it_name', models.CharField(max_length=200)),
                ('city_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('it_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.itineraries')),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landmark')),
            ],
        ),
    ]
