# Generated by Django 5.0.3 on 2024-03-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandmarkIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('url_for_image', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField(default=0.0)),
                ('lon', models.FloatField(default=0.0)),
                ('place', models.CharField(default='Unknown', max_length=100)),
                ('facing', models.CharField(default='Unknown', max_length=100)),
                ('speed', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
    ]
