# Generated by Django 5.0.3 on 2024-04-22 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_itineraryitems_landmark_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraries',
            name='end_date',
            field=models.DateField(default=datetime.date(1, 1, 1)),
        ),
    ]
