# Generated by Django 5.0.3 on 2024-03-25 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_landmarkidentification'),
        ('api', '0003_remove_itineraryitems_landmark_and_more'),
    ]

    operations = [
    ]
