# Generated by Django 5.0.3 on 2024-04-13 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_landmarktags_usertags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='LandmarkTags',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
