# Generated by Django 5.0.3 on 2024-04-18 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tag_visitedlandmarks_rating_landmark_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landmark',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture_url',
        ),
    ]
