# Generated by Django 5.0.3 on 2024-04-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_landmark_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='description',
            field=models.CharField(default='Unknown', max_length=1000),
        ),
        migrations.AddField(
            model_name='visitedlandmarks',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
