# Generated by Django 5.0.3 on 2024-04-20 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_landmark_description_visitedlandmarks_image_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertags',
            name='username',
        ),
        migrations.AddField(
            model_name='usertags',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usertags',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
