# Generated by Django 5.0.3 on 2024-04-21 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_landmark_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itineraryitems',
            name='date_time',
        ),
        migrations.AddField(
            model_name='itineraryitems',
            name='trip_day',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='itineraryitems',
            name='landmark_name',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='api.landmark'),
        ),
        migrations.AlterField(
            model_name='itineraryitems',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='itineraryitems',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='usertags',
            name='architecture',
            field=models.FloatField(default=3, null=True),
        ),
        migrations.AlterField(
            model_name='usertags',
            name='art',
            field=models.FloatField(default=3, null=True),
        ),
        migrations.AlterField(
            model_name='usertags',
            name='beach',
            field=models.FloatField(default=3, null=True),
        ),
        migrations.AlterField(
            model_name='usertags',
            name='entertainment',
            field=models.FloatField(default=3, null=True),
        ),
        migrations.AlterField(
            model_name='usertags',
            name='food',
            field=models.FloatField(default=3, null=True),
        ),
        migrations.AlterField(
            model_name='usertags',
            name='hiking',
            field=models.FloatField(default=3, null=True),
        ),
        migrations.AlterField(
            model_name='usertags',
            name='history',
            field=models.FloatField(default=3, null=True),
        ),
        migrations.AlterField(
            model_name='usertags',
            name='mountains',
            field=models.FloatField(default=3, null=True),
        ),
        migrations.AlterField(
            model_name='usertags',
            name='museum',
            field=models.FloatField(default=3, null=True),
        ),
        migrations.AlterField(
            model_name='usertags',
            name='music',
            field=models.FloatField(default=3, null=True),
        ),
        migrations.AlterField(
            model_name='usertags',
            name='recreation',
            field=models.FloatField(default=3, null=True),
        ),
        migrations.AlterField(
            model_name='usertags',
            name='scenicViews',
            field=models.FloatField(default=3, null=True),
        ),
        migrations.AlterField(
            model_name='usertags',
            name='sports',
            field=models.FloatField(default=3, null=True),
        ),
    ]
